name: Build

on:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Build
        run: |
          npm i
          npm run build

      - name: Get Tailwind version
        run: echo "TAILWIND_VERSION=$(jq -r .dependencies.tailwindcss package.json)" >> $GITHUB_ENV
      - name: Push
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

          git add .
          git commit -m 'build(tailwindcss): ${{ env.TAILWIND_VERSION }}'
          git push
